Repository coders-school/simple-text-communicator, pull requests merged in 2024-02, with the labels that each got.

#11 starting hello world application
  communicator/.gitignore
  communicator/CMakeLists.txt
  communicator/main.cpp
  communicator/mainwindow.cpp
  communicator/mainwindow.h
  communicator/mainwindow.ui
Labels: Standard, Unknown user

#12 Add pre-commit-config yaml
  .pre-commit-config.yaml
Labels: Standard

#9 Uml diagram
  README.md
  res/diagram_uml
  res/uml.plantuml
Labels: Standard, Auto-closed

#14 Add clang format file
  .clang-format
Labels: Standard

#13 Basic version of github actions
  .github/workflows/ci_basic.yaml
  .pre-commit-config.yaml
  communicator/tests/CMakeLists.txt
  communicator/tests/exampleTest.cpp
Labels: Unknown user
